CREATE TABLE IF NOT EXISTS yy_product_snapshot (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source_platform VARCHAR(50) NOT NULL COMMENT '来源平台编码',
    sku_id VARCHAR(128) NOT NULL COMMENT '平台SKU ID',
    product_id VARCHAR(128) DEFAULT NULL COMMENT '平台商品ID',
    source_api VARCHAR(50) DEFAULT NULL COMMENT '来源API编码(hot/search)',
    drug_id BIGINT DEFAULT NULL COMMENT '关联yy_drug_master.id',
    fusion_confidence DECIMAL(3,2) DEFAULT NULL COMMENT '融合置信度',
    common_name VARCHAR(200) DEFAULT NULL COMMENT '通用名',
    barcode VARCHAR(64) DEFAULT NULL COMMENT '69码',
    approval_number VARCHAR(100) DEFAULT NULL COMMENT '批准文号',
    manufacturer VARCHAR(200) DEFAULT NULL COMMENT '厂家',
    specification VARCHAR(200) DEFAULT NULL COMMENT '规格',
    price_current DECIMAL(10,2) DEFAULT NULL COMMENT '当前供货价',
    stock_quantity INT DEFAULT 0 COMMENT '库存数量',
    product_data JSON NOT NULL COMMENT '标准化后的全部商品数据JSON',
    raw_data_payload JSON DEFAULT NULL COMMENT '解密后的原始响应',
    collected_at DATETIME DEFAULT NULL COMMENT '采集时间',
    synced_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '同步时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_platform_sku (source_platform, sku_id),
    KEY idx_drug_id (drug_id),
    KEY idx_common_name (common_name),
    KEY idx_barcode (barcode),
    KEY idx_approval_number (approval_number),
    KEY idx_price (price_current)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台商品快照表';
